language: ruby
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.10
  - 2.3.7
  - 2.4.6
  - 2.5.5
  - 2.6.3
  - ruby-head
  - jruby-9.2.6.0
  - jruby-19mode
  - jruby-head
matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
